[project]
name = "CDRxclimate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bokeh>=3.9.1",
    "cartopy>=0.25.0",
    "cdsapi>=0.7.6",
    "chord>=6.0.1",
    "dask[distributed]>=2025.10.0",
    "duckdb>=1.5.4",
    "flox>=0.11.2",
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "geoparquet-io>=1.2.0",
    "h5netcdf>=1.6.4",
    "holoviews>=1.22.1",
    "lexcube>=1.0.3",
    "marimo[recommended]>=0.23.16",
    "matplotlib>=3.10.6",
    "matplotlib-inline>=0.2.1",
    "mplcursors>=0.7.1",
    "netcdf4>=1.7.3",
    "numcodecs>=0.16.5",
    "numpy>=2.2.6",
    "pandas>=2.3.2",
    "plotly>=6.9.0",
    "polars>=1.43.1",
    "psutil>=5.9.0",
    "pyarrow>=24.0.0",
    "pydeck>=0.9.2",
    "pylabtools>=2.0.1b0",
    "rioxarray>=0.19.0",
    "scipy>=1.15.3",
    "selenium>=4.45.0",
    "shapely",
    "sparse",
    "xarray>=2025.6.1",
    "xvec>=0.5.2",
    "zarr>=2.18.3",
]
