from datetime import timezone, datetime

import xarray as xr
import zarr
from numcodecs import Blosc
from pathlib import Path
from typing import Union

from zarr.codecs import BloscCodec
# add progress bar to zarr

import sys
sys.path.append(str(Path(__file__).parent.parent.parent))  # Add the parent directory to
print(sys.path)

from test.zarr_cube.zarr_local.nc_to_zarr import DEFAULT_CHUNKS, DEFAULT_COMPRESSOR, _infer_chunks_from_store, _build_encoding, _safe_chunks, _check_time_overlap, _store_size, _update_time_attrs

def _safe_chunks(ds: xr.Dataset, chunks: dict) -> dict:
    """
    clamp the chunk sizes to the dataset dimensions to avoid chunk sizes larger than the dimension size
    """
    return {
        dim: min(size, ds.dims[dim]) for dim, size in chunks.items() if dim in ds.dims
    }
def write_zarr_from_ds(
        ds: xr.Dataset, zarr_path: Union[str, Path],
        chunks:dict = None,
        compresor: BloscCodec = None,
        float_dtype: str = "float32",
        extra_attrs: dict = None,
) -> xr.Dataset:
    """
    Write an xarray Dataset to a Zarr store with specified compression and chunking. (Zarr V3) (mode='w')
    Use this function when the dataset is in memory and rather than reading from a file.

    Parameters:
    - ds: xarray.Dataset
        The dataset to be written to Zarr.
    - zarr_path: str or Path
        The path where the Zarr store will be created.
    - chunks: dict, optional
        A dictionary specifying the chunk sizes for each dimension.
    - compresor: BloscCodec, optional
        A Blosc codec for compression. If None, default compression will be used.
    - float_dtype: str, optional
        The data type for floating-point variables. Default is "float32".
    - extra_attrs: dict, optional
        Additional attributes to add to the dataset before writing.

    Returns:
    - xr.Dataset
        The dataset that was written to Zarr.
    """
    zarr_path = Path(zarr_path)
    chunks = _safe_chunks(ds, chunks or DEFAULT_CHUNKS)  # Ensure chunk sizes are valid clamp here
    compresor = compresor or DEFAULT_COMPRESSOR  # Use default compressor if not provided
    # Ensure the zarr_path is a Path object
    ds = ds.chunk(chunks)  # Apply chunking if the dataset is not already chunked


    attrs =dict(ds.attrs)  # Copy existing attributes
    attrs.setdefault("Conventions", "CF-1.8")  # Ensure CF conventions are set

    if "lat" in ds.coords and "lon" in ds.coords:
        attrs["geospatial_lat_min"] = float(ds.lat.min())
        attrs["geospatial_lat_max"] = float(ds.lat.max())
        attrs["geospatial_lon_min"] = float(ds.lon.min())
        attrs["geospatial_lon_max"] = float(ds.lon.max())
        attrs["geospatial_lat_resolution"] = abs(float(ds.lat.diff("lat").mean()))
        attrs["geospatial_lon_resolution"] = abs(float(ds.lon.diff("lon").mean()))

    if "time" in ds.coords and len(ds.time) > 0:
        t =ds.indexes["time"]
        attrs["time_coverage_start"] = str(t.min())
        attrs["time_coverage_end"] = str(t.max())
    attrs["date_created"] =  datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    attrs["source"] = "Generated by write_zarr_from_ds function"
    attrs["zarr_version"] = zarr.__version__
    attrs["xarray_version"] = xr.__version__

    # Apply extra attributes if provided
    if extra_attrs:
        attrs.update(extra_attrs)

    ds=ds.assign_attrs(attrs)  # Assign the updated attributes to the dataset
    encoding = _build_encoding(ds, chunks, compresor, float_dtype)  # Build encoding for Zarr

    print(f"[write] writing {list(ds.data_vars)} to {zarr_path} with chunks={chunks} and compressor={compresor}")
    ds.to_zarr(zarr_path, zarr_format=3, mode='w', encoding=encoding, consolidated=True, compute=True)  # Write to Zarr with specified encoding
    result_ds = xr.open_zarr(zarr_path, consolidated=True)  # Reopen the Zarr store to verify
    print(f"[write] {_store_size(zarr_path)} bytes written to {zarr_path}")
    return result_ds

def append_zarr_from_ds(
        ds: xr.Dataset, zarr_path: Union[str, Path],
        append_dim: str = "time",
        check_overlap: bool = True,
) -> xr.Dataset:
    """
    Append an xarray Dataset to an existing Zarr store along a specified dimension. (Zarr V3) (mode='a')

    Parameters:
    - ds: xarray.Dataset
        The dataset to be appended to the Zarr store.
    - zarr_path: str or Path
        The path to the existing Zarr store.
    - append_dim: str, optional
        The dimension along which to append the data. Default is "time".
    - check_overlap: bool, optional
        If True, checks for overlapping data along the append dimension and raises an error if found.

    Returns:
    - xr.Dataset
        The dataset after appending to the Zarr store.
    """
    
    zarr_path = Path(zarr_path)
    if not zarr_path.exists():
        raise FileNotFoundError(f"Zarr store at {zarr_path} does not exist. Use write_zarr_from_ds first.")

    existing_ds = xr.open_zarr(zarr_path, consolidated=True)  # Open existing Zarr store
    existing_len = existing_ds.dims.get(append_dim, 0)
    
    # inherit chunk from existing dataset so shapes stay the same
    existing_chunks = _infer_chunks_from_store(zarr_path, existing_ds)
    safe_chunks = _safe_chunks(ds, existing_chunks)  # Ensure chunk sizes are valid
    ds = ds.chunk(safe_chunks)  # Apply safe chunking to the new dataset
    
    if check_overlap:
        _check_time_overlap(existing_ds, ds)

    ## only keeo variables that are in both datasets
    ds = ds[list(set(existing_ds.data_vars).intersection(ds.data_vars))]
    _update_time_attrs(zarr_path, existing_ds, ds)

    ds.to_zarr(
        zarr_path, zarr_format=3, mode='a', append_dim=append_dim, compute=True, consolidated=True)
    result =xr.open_zarr(zarr_path, consolidated=True)  # Reopen the Zarr store to verify
    print(f"[append] {append_dim} dimension length: {existing_len} -> {result.dims.get(append_dim, 0)}")
    existing_ds.close()
    return result

